runtime: nodejs16

env_variables:
  REACT_APP_ETH_MAINNET_CHAIN_ID: "1"
  REACT_APP_ETH_MAINNET_RPC_URL_1: "https://mainnet.infura.io/v3/3bb2facc1ba34c21ac433006dea3015d"
  REACT_APP_ETH_MAINNET_RPC_URL_2: "https://mainnet.infura.io/v3/32cc1fd7fe8d4ad5aa6e4c2a18e90839"
  REACT_APP_BACKEND_URL: "https://hugiris.de.r.appspot.com"
